apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: dv-ubuntu-focal
spec:
  storage:
    accessModes:
      - ReadWriteOnce 
    volumeMode: Filesystem 
    resources:
      requests:
        storage: 10Gi
  source:
    registry:
      url: "docker://tedezed/ubuntu-container-disk:20.0"